In [1]:
import torch 

In [2]:
## first basics 

torch.__version__

'2.1.2+cu118'

In [3]:
## Creating random variable 

torch.tensor([[1,2,3],
              [4,5,6]],dtype=torch.float32).shape

torch.Size([2, 3])

In [4]:
torch.ones((1,4)).to(dtype=torch.int16)

tensor([[1, 1, 1, 1]], dtype=torch.int16)

In [5]:
device=('cuda' if torch.cuda.is_available() else 'cpu')

In [6]:
print(device)

cuda


In [7]:
x=torch.rand(size=(2,3),requires_grad=True)

In [8]:
y=x**2

In [9]:
y

tensor([[0.2243, 0.0811, 0.3497],
        [0.7096, 0.6624, 0.7769]], grad_fn=<PowBackward0>)

In [10]:
y.backward

<bound method Tensor.backward of tensor([[0.2243, 0.0811, 0.3497],
        [0.7096, 0.6624, 0.7769]], grad_fn=<PowBackward0>)>

In [11]:
x.grad

In [18]:
x.add_(torch.tensor([1.0],requires_grad=True))

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

unsqueeze

In [31]:
x1=torch.tensor([[1,2,3],
                 [4,5,6]])

print(x1.shape)

print(x1)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [39]:
x1.unsqueeze(dim=1).squeeze(dim=1)==x1

tensor([[True, True, True],
        [True, True, True]])

In [21]:
x.add(torch.tensor([1.0]),dim=0) ## no option of dim chossing parameters 


TypeError: add() got an unexpected keyword argument 'dim'

In [28]:
x.detach().numpy()

array([[0.75803953, 0.43997502, 0.6763543 ],
       [0.5081974 , 0.90638834, 0.01155788]], dtype=float32)

In [40]:
## autograd 

In [68]:
x=torch.tensor([1,2,3],dtype=torch.float32,requires_grad=True).to(device=device)
y=torch.square(x)
z=y+2

print(y.requires_grad)
print(z.requires_grad)

print('z=', z)

True
True
z= tensor([ 3.,  6., 11.], device='cuda:0', grad_fn=<AddBackward0>)


In [69]:

dl_dz=torch.ones(3).to(device=device)
z.backward(dl_dz)

In [70]:
print(x.grad)

None


/tmp/ipykernel_119265/3014308063.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(x.grad)


In [53]:
print(z.requires_grad)

True


In [54]:
print(x.grad)

None


/tmp/ipykernel_119265/3014308063.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(x.grad)


In [71]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create tensor x on the defined device
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True).to(device=device)

# Calculate y and z
y = torch.square(x)
z = y + 2

print(y.requires_grad)  # Check if y requires grad
print(z.requires_grad)  # Check if z requires grad

print('z=', z)

# Define the gradients for z (dummy values in this case)
dl_dz = torch.ones(3).to(device=device)

# Backpropagate the gradients
z.backward(dl_dz)

# Access and print gradients of x
print(x.grad)

True
True
z= tensor([ 3.,  6., 11.], device='cuda:0', grad_fn=<AddBackward0>)
None


/tmp/ipykernel_119265/825919224.py:22: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(x.grad)


In [1]:

import torch
# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create tensor x on the defined device
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True).to(device=device)

# Calculate y and z
y = torch.square(x)
z = y + 2

print(y.requires_grad)  # Check if y requires grad
print(z.requires_grad)  # Check if z requires grad

print('z=', z)

# Backpropagate the gradients
z.backward(torch.ones_like(z))

# Access and print gradients of x
print(x.grad)


True
True
z= tensor([ 3.,  6., 11.], device='cuda:0', grad_fn=<AddBackward0>)
None


/tmp/ipykernel_156404/3329655305.py:21: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(x.grad)


In [5]:
import torch

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create tensor x on the defined device
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True).to(device=device)

# Calculate y and z
y = torch.square(x)
z = y + 2

print(y.requires_grad)  # Check if y requires grad
print(z.requires_grad)  # Check if z requires grad

print('z=', z)

# Backpropagate the gradients
z.backward(torch.ones_like(z))

# Access and print gradients of x's leaf ancestors
print(x.grad)


True
True
z= tensor([ 3.,  6., 11.], device='cuda:0', grad_fn=<AddBackward0>)
None


/tmp/ipykernel_156404/1839270234.py:22: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(x.grad)


In [3]:
x.is_leaf

False

In [4]:
y.is_leaf

False