In [50]:
import torch

In [60]:
#device=('cuda' if torch.cuda.is_available() else 'cpu')
device='cpu'

In [61]:
## Simple Backpropagation 
x=torch.tensor([1,2,3,4],dtype=torch.float32).to(device=device)
true_m=torch.tensor([2],dtype=torch.float32).to(device=device)
true_b=torch.tensor([3],dtype=torch.float32).to(device=device)
y_true=x*true_m+true_b

print(y_true)

tensor([ 5.,  7.,  9., 11.])


In [62]:
w_m=torch.rand(1,dtype=torch.float32,requires_grad=True).to(device=device)
w_b=torch.rand(1,dtype=torch.float32,requires_grad=True).to(device=device)


In [63]:
w_m

tensor([0.3263], requires_grad=True)

In [64]:
## def forward pass

def forward(X):
    return X*w_m+w_b

In [65]:
## defining the backward pass 

def criterion(y_true,y_pred):
    loss=torch.square(y_true-y_pred).mean()
    return loss


In [67]:
## Defining the training parameters 
num_epochs=200
lr=0.001


In [68]:
##training
for epoch_num in range(num_epochs):
    y_pred=forward(x)
    loss=criterion(y_true,y_pred)
    
    loss.backward()
    dl_dw=w_m.grad.to(device=device)
    dl_db=w_b.grad.to(device=device)

    with torch.no_grad():
        w_m -=lr*dl_dw
        w_b-=lr*dl_db

    if epoch_num%10==0:
       
        print('Epoch Num: {}'.format(epoch_num))
        print('loss= {:.3f}\tw_m: {:.3f}\tw_b: {:.3f}'.format(loss.item(),w_m.item(),w_b.item()))

    w_m.grad.zero_()
    w_b.grad.zero_()

Epoch Num: 0
loss= 44.638	w_m: 0.363	w_b: 0.783
Epoch Num: 10
loss= 31.976	w_m: 0.693	w_b: 0.901
Epoch Num: 20
loss= 22.935	w_m: 0.973	w_b: 1.001
Epoch Num: 30
loss= 16.478	w_m: 1.208	w_b: 1.086
Epoch Num: 40
loss= 11.868	w_m: 1.407	w_b: 1.158
Epoch Num: 50
loss= 8.575	w_m: 1.575	w_b: 1.220
Epoch Num: 60
loss= 6.223	w_m: 1.717	w_b: 1.273
Epoch Num: 70
loss= 4.544	w_m: 1.836	w_b: 1.319
Epoch Num: 80
loss= 3.344	w_m: 1.937	w_b: 1.358
Epoch Num: 90
loss= 2.486	w_m: 2.022	w_b: 1.392
Epoch Num: 100
loss= 1.873	w_m: 2.093	w_b: 1.421
Epoch Num: 110
loss= 1.435	w_m: 2.153	w_b: 1.446
Epoch Num: 120
loss= 1.122	w_m: 2.204	w_b: 1.468
Epoch Num: 130
loss= 0.897	w_m: 2.247	w_b: 1.487
Epoch Num: 140
loss= 0.737	w_m: 2.282	w_b: 1.504
Epoch Num: 150
loss= 0.621	w_m: 2.312	w_b: 1.519
Epoch Num: 160
loss= 0.538	w_m: 2.338	w_b: 1.533
Epoch Num: 170
loss= 0.478	w_m: 2.359	w_b: 1.544
Epoch Num: 180
loss= 0.435	w_m: 2.376	w_b: 1.555
Epoch Num: 190
loss= 0.404	w_m: 2.391	w_b: 1.565


In [69]:
y_pred=y_pred.detach().numpy()

In [70]:
y_pred

array([ 3.9724553,  6.3729706,  8.773486 , 11.174002 ], dtype=float32)

In [16]:
loss

tensor(46.1384, device='cuda:0', grad_fn=<MeanBackward0>)