In [1]:
## Learning thr basics of torch 

In [1]:
import torch 

In [197]:
x=torch.empty(1)

In [198]:
x=torch.rand(5,3) # by default requires grad is False, and the datatype is float32

In [199]:
x.size()

torch.Size([5, 3])

In [200]:
x.shape

torch.Size([5, 3])

In [201]:
x.dtype #default datatype

torch.float32

In [202]:
x=torch.rand(5,3, dtype=torch.float64,requires_grad=True)

In [203]:
print('x.type= {}, x.requires_grad= {}'.format(x.dtype,x.requires_grad))

x.type= torch.float64, x.requires_grad= True


In [204]:
x=torch.zeros(2,2,3)

In [205]:
x.shape

torch.Size([2, 2, 3])

In [206]:
x.dtype

torch.float32

In [207]:
x=torch.ones(1,2,3,4,dtype=torch.int16)

In [208]:
x.dtype

torch.int16

In [209]:
x

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]],

         [[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]]], dtype=torch.int16)

In [210]:
#creating torch tensor 

x=torch.tensor([[5.5,3,2]]) ## mix datatype

In [211]:
x.dtype

torch.float32

In [212]:
x

tensor([[5.5000, 3.0000, 2.0000]])

In [213]:
x=torch.tensor([[5.5,3,2]],dtype=torch.int16) ## mix datatype

/tmp/ipykernel_27375/4144407515.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  x=torch.tensor([[5.5,3,2]],dtype=torch.int16) ## mix datatype


In [214]:
x.shape

torch.Size([1, 3])

In [185]:
x.requires_grad ## by default the require grad is false. This is required for backpropagation 

False

In [186]:
## Creating tensor with requires_grad == True 

In [187]:
x=torch.tensor([1,2,3],dtype=torch.float16,requires_grad=True) ## only possible for float not int 

In [188]:
x.requires_grad

True

In [189]:
## How about tensor created using rand or zeros 

In [190]:
x=torch.ones(5)

In [191]:
x.requires_grad

False

### Tensor Addition, Multiplication, Division of two or more tensors

In [192]:
# Can we add tensor or two datatypes

a=torch.tensor([1,2,3])
print(a.dtype)
print(a.shape)

torch.int64
torch.Size([3])


In [193]:
b=torch.ones(3,dtype=torch.float64)
print(b.dtype)
print(b.shape)

torch.float64
torch.Size([3])


In [194]:
c=a+b # Adding with different dtypes will have dtype with higher number of float number (float 64>int64; so float64 will be chosen)
print(b.dtype)
print(b.shape)

torch.float64
torch.Size([3])


In [195]:
c

tensor([2., 3., 4.], dtype=torch.float64)

In [145]:
c_=torch.add(a,b)

In [146]:
c_==c

tensor([True, True, True])

Is there any difference between **torch.add()** vs simple **+** ? Any benefit to use one over other one. 

No there is not any significant difference between using either of these. Unlike tf,  we donot have to care about graph execution. 

In [148]:
## Adding with different shape
a=torch.tensor([[1,4,3]])
print(a.dtype)
print(a.shape)

torch.int64
torch.Size([1, 3])


In [149]:
b=torch.ones(2,3)#shape=2,3, and dtype=float32
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [150]:
c=a+b
print(c)
print(c.shape)
print(c.dtype)
## So adding two tensors with different shape is simiar to numpy or tensorflow 

tensor([[2., 5., 4.],
        [2., 5., 4.]])
torch.Size([2, 3])
torch.float32


### Multiplication 

In [151]:
d=torch.tensor([[2,3,4]]) ## Element wise multipicatio

In [152]:
e=torch.tensor([[4,6,8],
                [8,9,5]])

In [153]:
f=torch.tensor([8])

In [154]:
e

tensor([[4, 6, 8],
        [8, 9, 5]])

In [155]:
d*e ## element wise multiplication ; similar to torch.mul()

tensor([[ 8, 18, 32],
        [16, 27, 20]])

In [156]:
e*f # element wise 

tensor([[32, 48, 64],
        [64, 72, 40]])

In [157]:
torch.mul(d,e)

tensor([[ 8, 18, 32],
        [16, 27, 20]])

### Operation to itself

In [158]:
a=torch.tensor([1,2,4])

In [160]:
c=a+2 ## elemet wise 

In [162]:
a # a is still the asame

tensor([1, 2, 4])

In [163]:
a.add_(2)

tensor([3, 4, 6])

In [164]:
a ## a changes itself


tensor([3, 4, 6])

What is the difference of **a=a+2** and **a.add_(2)** ? 

- **Saves memory**: Creates a new tensor "a" by adding 2 to original tensor "a". 

- **Preserving the Computational Graph**: During backpropagation, PyTorch needs to traverse the computational graph from the output back to the input. If an in-place operation like a.add_(2) modifies a tensor that is part of this graph, it can lead to incorrect gradients or errors because the original value of the tensor, which might be needed for gradient calculation, is lost.

### Conversion from NumPy to Torch Tensor and vice-versa 

In [216]:
import numpy as np 


In [228]:
a=np.ones(5)
b=torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [229]:
a +=1
print(a)

[2. 2. 2. 2. 2.]


In [230]:
print(b)  ## Here you can observe change in one can change in other 

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [238]:
## Converting to numpy 

x1=torch.tensor([1,2,3,4])

y1=x1.numpy()

In [240]:
type(y1)

numpy.ndarray

### Creating tensor in GPU

By default the tensors are created in ""CPU"", so here we will learn creating tensors in GPU. 

In [231]:
x

tensor([[5, 3, 2]], dtype=torch.int16)

In [245]:
if torch.cuda.is_available():

    device=torch.device("cuda")
    y=torch.ones_like(x,dtype=torch.float32,device=device) ## Creates tensors on cuda
    x=x.to(device) ## Or, we can just use "cuda" instead
    z=x+y
    print("z.device: {}".format(z.device))
    


z.device: cuda:0


In [236]:
z.device

device(type='cuda', index=0)

In [244]:
try: 
    z.numpy()
    
except: 
    print("Can't convert to numpy directly from CPU")
    z.to("cpu").numpy

Can't convert to numpy directly from CPU
