## Autograd

In [1]:
import torch 


In [2]:
# this is similar to tf.GradientTape() in tensorflow 
# Create a variable with requires_grad=True

x=torch.tensor([1,2,3],dtype=torch.float32,requires_grad=True)
y=x+2
z=torch.square(y)
z1=torch.square(y)
print(z.requires_grad) #so y is also created with requires_grad=True



True


In [3]:
x.is_leaf

True

In [4]:
z.mean()

tensor(16.6667, grad_fn=<MeanBackward0>)

In [5]:
## Calculating dl/dx (used for optimization in training process)
# defube dl/dz (l=loss) 
dl_dz=torch.ones(3)
z.backward(dl_dz)

print(x.grad) #dl/dx 

tensor([ 6.,  8., 10.])


In [6]:
print(y.grad_fn)
print(z.grad_fn)

In [7]:
## We can also define z.backward() wigtou defining dl_dz. But we have to convert z to scaler 
z1=z1.mean()
z1.backward()
x.grad

## how does it work when we take mean, learn it later

tensor([ 8.0000, 10.6667, 13.3333])

In [24]:
x.grad

tensor([ 8.0000, 10.6667, 13.3333])

In [8]:
## Grad Detach 

In [1]:
## Grad Accumulation 
import torch

# Simple Backpropagation 

In [2]:
x=torch.tensor([1,2,3,4],dtype=torch.float32)
true_m=torch.tensor([2],dtype=torch.float32)
true_b=torch.tensor([4],dtype=torch.float32)
y_true=x*true_m+true_b

In [3]:
w_m=torch.rand(1,dtype=torch.float32,requires_grad=True)
w_b=torch.rand(1,dtype=torch.float32,requires_grad=True)

In [4]:
y_true

tensor([ 6.,  8., 10., 12.])

In [5]:
def forward_pass(X):
    return X * w_m + w_b

In [6]:
def loss_fnc(y_true,y_pred):
    loss=torch.square(y_true-y_pred).mean()
    return loss 

In [7]:
## Define the training parameters 

EPOCHS=100
lr=0.001

for epoch in range(EPOCHS):
    y_pred=forward_pass(x)
    loss=loss_fnc(y_true,y_pred)
    
    loss.backward()
    dl_dw=w_m.grad
    dl_db=w_b.grad

    with torch.no_grad():
        w_m -=lr*dl_dw
        w_b-=lr*dl_db

    if epoch%10==0:
        print('Epoch Num: {}'.format(epoch))
        print('loss= {:.3f}\tw_m: {:.3f}\tw_b: {:.3f}'.format(loss.item(),w_m.item(),w_b.item()))
        
    w_m.grad.zero_()
    w_b.grad.zero_()


Epoch Num: 0
loss= 45.753	w_m: 0.935	w_b: 0.114
Epoch Num: 10
loss= 33.136	w_m: 1.264	w_b: 0.236
Epoch Num: 20
loss= 24.124	w_m: 1.541	w_b: 0.341
Epoch Num: 30
loss= 17.687	w_m: 1.774	w_b: 0.431
Epoch Num: 40
loss= 13.087	w_m: 1.971	w_b: 0.508
Epoch Num: 50
loss= 9.801	w_m: 2.137	w_b: 0.575
Epoch Num: 60
loss= 7.451	w_m: 2.277	w_b: 0.633
Epoch Num: 70
loss= 5.771	w_m: 2.394	w_b: 0.683
Epoch Num: 80
loss= 4.568	w_m: 2.493	w_b: 0.727
Epoch Num: 90
loss= 3.707	w_m: 2.576	w_b: 0.765


2.284


In [24]:
loss.item()

3.0080771446228027